### ISSUE TITLE
Multiple runs triggered by a single deployment

### ISSUE THREAD

**Issue by mcascone** [activescott/automate-environment-deployment-approval#59]
When configured according to the docs, I am seeing multiple `auto-approve` runs triggered by a single deployment.

I think it's due to the use of `on: deployment_status` as opposed to `on: deployment`?

It's also due to using the personal PAT, vs the github token; the latter is automatically prevented from causing infinite loops.

Thanks!

**Comment by activescott** [comment]
Yes, it was designed to fetch fetch all ALL pending deploys/runs and approve them. This is done at https://github.com/activescott/automate-environment-deployment-approval/blob/e84337cb8d57f43a58b5490c55ef0b5c446101f2/src/approver.ts#L13

The `on:` trigger is what you would use in your workflow, so you could run it on any trigger, but when it runs, it's still going to fetch them all.

As for the token, I remember I had to use a PAT as github token from workflows didn't seem to have the permissions to either find or approve the workflows. I have a note about that in the readme at https://github.com/activescott/automate-environment-deployment-approval?tab=readme-ov-file#1-create-a-personal-access-token

I'm going to close this one, but will also reply to your feature request.
